// IMPORTANT: This file must be generated by the FlutterFire CLI.
// See the README.md for setup instructions.
//
// Run: flutterfire configure
// in the project root after creating your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  // ─── REPLACE THESE WITH YOUR ACTUAL VALUES ──────────────────────
  // Get these from: Firebase Console > Project Settings > Your Apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjplyZxUpbk8ibmLuYeHWoubT9HYVhH7E',
    appId: '1:729004879750:web:3987681fa9f407455f4607',
    messagingSenderId: '729004879750',
    projectId: 'chit-chat-64d4b',
    authDomain: 'chit-chat-64d4b.firebaseapp.com',
    storageBucket: 'chit-chat-64d4b.firebasestorage.app',
    measurementId: 'G-MQWRKHL4RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKovusKlVQ1y8VFZ9WTp3-i6oTD1WzXfE',
    appId: '1:729004879750:android:81752778372bccce5f4607',
    messagingSenderId: '729004879750',
    projectId: 'chit-chat-64d4b',
    storageBucket: 'chit-chat-64d4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3byIU1X7PFJtx0K-A3UGXAPrmoSV2FBk',
    appId: '1:729004879750:ios:739a4009996c29695f4607',
    messagingSenderId: '729004879750',
    projectId: 'chit-chat-64d4b',
    storageBucket: 'chit-chat-64d4b.firebasestorage.app',
    iosBundleId: 'com.tripplanner.tripPlannerApp',
  );

  // ────────────────────────────────────────────────────────────────
}